---
title: "Lab 09 - Grading the professor, Pt. 1"
author: "Insert your name here"
date: "Insert date here"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(tidymodels)
library(openintro)
```

### Exercise 1-3
```{R}

evals2 <- evals

print(head(evals2,10))

## 1
hist(evals2$score)

##2

evals2 %>%
  ggplot( mapping=aes(x=score, y=bty_avg)) +
  geom_point()+
  stat_smooth(method=lm)

##3

evals2 %>%
  ggplot( mapping=aes(x=score, y=bty_avg)) +
  geom_jitter(width=0.4)+ # generating random varaible and jitter the dots. 
  stat_smooth(method=lm)
```

### Exercise 4-8

```{R}
##4
m_bty<-lm(score~bty_avg, evals2)
summary(m_bty)

##5,6, 7, 8 
evals2 %>%
  ggplot( mapping=aes(x=score, y=bty_avg)) +
  geom_point()+
  stat_smooth(method=lm, se=FALSE, color="orange")
```

Model R^2 = 0.035
this model explain the 3.5% of the total variance. 

bty_avg is significant predictor for the score.
intercept is 3.388
This meas that if the bty_avg=0, the score is 3.88034





## Exercise 9-15

```{r}
##9
m_gen<-lm(score~as.factor(gender), evals2)
summary(m_gen)

##10
m_rank<-lm(score~as.factor(rank), evals2)
summary(m_rank)


m_rank<-lm(score~as.factor(rank), evals2)
summary(m_rank)

table(evals2$rank)

##11

evals2<-evals2 %>%
  mutate(rankre = relevel(rank,ref="tenure track" ))

ref_rank<-lm(score~ rankre, evals2)
summary(ref_rank)



evals2 <- evals2 %>%
  mutate(tenure_eligible = case_when(
    rank == "teaching" ~ "no",
    rank == "tenure track" ~ "yes",
    rank == "tenured" ~ "yes"
  ))

m_tenure_eligible<-lm(score~as.factor(tenure_eligible), evals2)
summary(m_tenure_eligible)

```
male
4.092982 + 0.14151
female 4.092982 + 0 

teaching: 4.28 + 0
tenured: 4.28 - 0.12968
tenured track : 4.28-0.14518

tenure track = 4.15 
teacing = 4.15+0.129
tenured = 4.15-0.01550


R^2=0.01
this model explain 1% of the variance in the DV 
No  = 4.28
Yes = 4.28 - 0.1406


